/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppDlqRouteImport } from './routes/_app.dlq'
import { Route as AppJobsNewRouteImport } from './routes/_app.jobs.new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppDlqRoute = AppDlqRouteImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dlq': typeof AppDlqRoute
  '/jobs': typeof AppJobsRouteWithChildren
  '/jobs/new': typeof AppJobsNewRoute
}
export interface FileRoutesByTo {
  '/dlq': typeof AppDlqRoute
  '/jobs': typeof AppJobsRouteWithChildren
  '/': typeof AppIndexRoute
  '/jobs/new': typeof AppJobsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/dlq': typeof AppDlqRoute
  '/_app/jobs': typeof AppJobsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/jobs/new': typeof AppJobsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dlq' | '/jobs' | '/jobs/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/dlq' | '/jobs' | '/' | '/jobs/new'
  id:
    | '__root__'
    | '/_app'
    | '/_app/dlq'
    | '/_app/jobs'
    | '/_app/'
    | '/_app/jobs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dlq': {
      id: '/_app/dlq'
      path: '/dlq'
      fullPath: '/dlq'
      preLoaderRoute: typeof AppDlqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppJobsRoute
    }
  }
}

interface AppJobsRouteChildren {
  AppJobsNewRoute: typeof AppJobsNewRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsNewRoute: AppJobsNewRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppRouteChildren {
  AppDlqRoute: typeof AppDlqRoute
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDlqRoute: AppDlqRoute,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
